name: Generate Facebook Product Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # Runs daily at 2am AWST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install base dependencies
        run: |
          pip install requests requests-oauthlib

      - name: Generate BrickLink product feed
        run: python generate_facebook_feed.py
        env:
          BL_CONSUMER_KEY: ${{ secrets.BL_CONSUMER_KEY }}
          BL_CONSUMER_SECRET: ${{ secrets.BL_CONSUMER_SECRET }}
          BL_TOKEN_VALUE: ${{ secrets.BL_TOKEN_VALUE }}
          BL_TOKEN_SECRET: ${{ secrets.BL_TOKEN_SECRET }}

      - name: Install Playwright and browser
        run: |
          pip install playwright
          playwright install

      - name: Scrape titles, colors, and image links for 5 items
        run: python fetch_storefront_data.py

      - name: Replace original feed with updated image links
        run: mv meta_product_feed_with_images.csv meta_product_feed.csv

      - name: Deploy to GitHub Pages (via PAT)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          publish_branch: main
