name: Daily BrickLink Rarity Update

on:
  schedule:
    - cron: '0 18 * * *'  # 2am AWST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests requests_oauthlib

      - name: Run rarity updater
        env:
          BL_CONSUMER_KEY: ${{ secrets.BL_CONSUMER_KEY }}
          BL_CONSUMER_SECRET: ${{ secrets.BL_CONSUMER_SECRET }}
          BL_TOKEN_VALUE: ${{ secrets.BL_TOKEN_VALUE }}
          BL_TOKEN_SECRET: ${{ secrets.BL_TOKEN_SECRET }}
        run: python main.py
